# Generated by Django 5.1.1 on 2024-09-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_todo_importance_todo_urgency_alter_todo_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='description',
            new_name='content',
        ),
    ]
