# Generated by Django 5.1.1 on 2024-10-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_description_todo_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='content',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='todo',
            name='importance',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='重要度'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='urgency',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='緊急度'),
        ),
    ]
